"""
Wrapper for OpenAI types to make them compatible with Pydantic.

Pydantic doesn't support Iterable[T] well, so we use List[T] instead for tool_calls,
https://github.com/pydantic/pydantic/issues/9541

Otherwise we are using OpenAI SDK types directly.
"""

from typing import (
    Any,
    Iterable,
    List,
    Literal,
    Optional,
    TypeAlias,
    Union,
)

from openai.types.chat import (
    ChatCompletionContentPartTextParam,
    ChatCompletionDeveloperMessageParam,
    ChatCompletionFunctionMessageParam,
    ChatCompletionMessageToolCallParam,
    ChatCompletionSystemMessageParam,
    ChatCompletionUserMessageParam,
)
from openai.types.chat.chat_completion_assistant_message_param import (
    Audio,
    ContentArrayOfContentPart,
    FunctionCall,
)
from pydantic import TypeAdapter
from typing_extensions import Required, TypedDict

from kiln_ai.utils.usage import MessageUsage

# Name of the synthetic tool that carries a structured output back from the
# model in function-calling structured output modes. The user never defined it,
# and the adapter unwraps it into the run's output rather than running it — so
# consumers reasoning about "tools the model chose to call" must exclude it, and
# consumers rendering a trace should show its arguments as the model's answer.
TASK_RESPONSE_TOOL_NAME = "task_response"


class ChatCompletionAssistantMessageParamWrapper(TypedDict, total=False):
    """
    Almost exact copy of ChatCompletionAssistantMessageParam, but two changes.

    First change: List[T] instead of Iterable[T] for tool_calls. Addresses pydantic issue.
    https://github.com/pydantic/pydantic/issues/9541

    Second change: Add reasoning_content to the message. A LiteLLM property for reasoning data.
    """

    role: Required[Literal["assistant"]]
    """The role of the messages author, in this case `assistant`."""

    audio: Optional[Audio]
    """Data about a previous audio response from the model.

    [Learn more](https://platform.openai.com/docs/guides/audio).
    """

    content: Union[str, Iterable[ContentArrayOfContentPart], None]
    """The contents of the assistant message.

    Required unless `tool_calls` or `function_call` is specified.
    """

    reasoning_content: Optional[str]
    """The reasoning content of the assistant message. 
    
    A LiteLLM property for reasoning data: https://docs.litellm.ai/docs/reasoning_content
    """

    function_call: Optional[FunctionCall]
    """Deprecated and replaced by `tool_calls`.

    The name and arguments of a function that should be called, as generated by the
    model.
    """

    name: str
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """

    refusal: Optional[str]
    """The refusal message by the assistant."""

    tool_calls: List[ChatCompletionMessageToolCallParam]
    """The tool calls generated by the model, such as function calls."""

    latency_ms: Optional[int]
    """Time spent waiting on this specific LLM API call in milliseconds."""

    usage: Optional[MessageUsage]
    """Token usage and cost for the LLM call that produced this assistant message.

    Set per-call (one record per LLM response, not per logical turn). Stripped
    before sending messages back to providers via KILN_ONLY_MESSAGE_FIELDS.
    Per-call latency lives on the message's `latency_ms` field — MessageUsage
    intentionally does not carry latency.
    """


class ChatCompletionToolMessageParamWrapper(TypedDict, total=False):
    content: Required[Union[str, Iterable[ChatCompletionContentPartTextParam]]]
    """The contents of the tool message."""

    role: Required[Literal["tool"]]
    """The role of the messages author, in this case `tool`."""

    tool_call_id: Required[str]
    """Tool call that this message is responding to."""

    kiln_task_tool_data: Optional[str]
    """The data for the Kiln task tool that this message is responding to.

    Formatted as `<project_id>:::<tool_id>:::<task_id>:::<run_id>`
    """

    is_error: Optional[bool]
    """Whether this tool message represents an error result."""

    error_message: Optional[str]
    """Human-readable error description when is_error is True."""


ChatCompletionMessageParam: TypeAlias = Union[
    ChatCompletionDeveloperMessageParam,
    ChatCompletionSystemMessageParam,
    ChatCompletionUserMessageParam,
    ChatCompletionAssistantMessageParamWrapper,
    ChatCompletionToolMessageParamWrapper,
    ChatCompletionFunctionMessageParam,
]


KILN_ONLY_MESSAGE_FIELDS: frozenset[str] = frozenset(
    {
        "latency_ms",
        "is_error",
        "error_message",
        "kiln_task_tool_data",
        "usage",
    }
)
"""Per-message fields kept on traces for UI/diagnostics. Providers reject unknown
keys, so these are stripped before sending to LiteLLM. Add new Kiln-only message
fields here when extending the wrappers above."""


def sanitize_messages_for_provider(messages: Iterable[Any]) -> list[Any]:
    """Return a copy of ``messages`` with ``KILN_ONLY_MESSAGE_FIELDS`` removed
    from any dict entries. Non-dict entries (e.g. LiteLLM ``Message`` objects)
    pass through unchanged. The input list and its dicts are not mutated."""
    sanitized: list[Any] = []
    for message in messages:
        # Traces mix TypedDict messages (which may carry kiln-only fields) with
        # LiteLLM Message pydantic objects returned from prior calls (which never
        # do). Only dicts need stripping; pass other types through untouched.
        if isinstance(message, dict):
            sanitized.append(
                {k: v for k, v in message.items() if k not in KILN_ONLY_MESSAGE_FIELDS}
            )
        else:
            sanitized.append(message)
    return sanitized


_trace_adapter: TypeAdapter[list[ChatCompletionMessageParam]] = TypeAdapter(
    list[ChatCompletionMessageParam]
)


def materialize_lazy_content(trace: Iterable[Any]) -> None:
    """Replace each message's lazily-validated `content` with the list it yields.

    Pydantic validates the wrappers' ``Iterable[...]``-typed fields into a lazy,
    single-use ``ValidatorIterator``. Serializing reads it, and a read empties it, so
    without this a trace would serialize correctly once and as ``content: []`` every
    time after - and any ``save_to_file`` on the same object would persist the empty
    version. The read is unavoidable; writing the result back in place is what makes
    it harmless.

    Scoped to ``content`` deliberately, and it needs to stay that way. ``content`` is
    the only ``Iterable[...]``-typed field across all six union members (``tool_calls``
    is a ``List``, which pydantic materializes eagerly). Widening this to "any iterable
    value" would also sweep in ``usage`` - and iterating a pydantic model yields its
    ``(name, value)`` pairs, so a ``MessageUsage`` would serialize as a list of pairs.

    Takes ``Iterable[Any]``, the same structural shape
    :func:`sanitize_messages_for_provider` uses - though for a different reason: that
    one is loose because its callers really do pass heterogeneous values, while here
    the callers pass a precise ``list[ChatCompletionMessageParam]`` and the
    ``Any`` exists only to make the write expressible. One union member declares
    ``content`` as ``str | None`` (the function role), so no tighter signature type
    checks, and ``typing.cast`` is banned repo-wide. The guard below still means only
    a message actually holding a lazy iterator is ever written to.

    Now that TaskRun runs this at validation, it also changes what ``save_to_file``
    persists for content-part traces - for the better. A lazy ``content`` on a user
    or tool message serialized as ``content: []`` (only the assistant branch read the
    iterator), silently dropping the parts; a materialized list persists them. The
    cost is cosmetic: a materialized ``list`` matches neither ``str`` nor
    ``generator`` in the union, so each dump of such a message emits one
    ``PydanticSerializationUnexpectedValue`` warning on stderr. Load-then-resave of a
    materialized trace is byte-identical.
    """
    for message in trace:
        if not isinstance(message, dict):
            continue
        content = message.get("content")
        if content is None or isinstance(content, (str, bytes, list, dict)):
            continue
        message["content"] = list(content)


def serialize_trace(trace: list[ChatCompletionMessageParam]) -> str:
    """Serialize a trace to the pretty-printed JSON that Kiln stores and displays.

    Not `json.dumps`: a validated trace is not plain data. Pydantic coerces the
    per-message `usage` key to a `MessageUsage` model (both in memory and when a
    TaskRun is loaded back off disk), and the stdlib encoder cannot serialize it.
    For an otherwise-plain trace this returns byte-for-byte what `json.dumps(...,
    indent=2, ensure_ascii=False)` returned, so stored traces render unchanged.

    Normalizes a lazily-validated `content` to a plain list in place first, so that
    serializing is repeatable and leaves the trace intact for whoever holds it - see
    :func:`materialize_lazy_content`.
    """
    materialize_lazy_content(trace)
    # warnings=False: every message with a key the wrappers don't declare, a
    # list-valued `content`, or a `Usage` in the `usage` slot fails to match a
    # union member and emits a six-line serializer warning - on every message, on
    # every eval-results request. The mismatch is not a defect: pydantic then falls
    # back to duck-typed inference, which is exactly what keeps the output
    # byte-identical to the `json.dumps` this replaced. Silencing it loses no signal
    # a test wouldn't catch first - TestSerializeTrace pins that parity, including
    # the unknown-key and unknown-role cases that rely on the fallback, so a pydantic
    # upgrade that tightened union serialization fails there rather than in a log.
    return _trace_adapter.dump_json(trace, indent=2, warnings=False).decode()


def trace_has_pending_client_tool_calls(
    trace: list[ChatCompletionMessageParam] | None,
) -> bool:
    """Return True if the trace ends with an assistant message awaiting client tool results.

    Structured-output flows use an internal ``task_response`` tool call; traces that end
    with only those calls are complete from the client's perspective for external tools.
    """
    if not trace:
        return False
    last_msg = trace[-1]
    if last_msg.get("role") != "assistant":
        return False
    tool_calls = last_msg.get("tool_calls") or []
    return any(
        isinstance(tc, dict)
        and (tc.get("function") or {}).get("name") != TASK_RESPONSE_TOOL_NAME
        for tc in tool_calls
    )
